#!/bin/bash
RETRIES=${RETRIES:-20}
PAUSE=${PAUSE:-10}

for n in $(seq ${RETRIES}); do
  echo "[${n}/${RETRIES}] ${*}"
  if eval "${*}"; then
    echo "[SUCC] ${n}/${RETRIES}"
    exit 0
  fi
  sleep ${PAUSE}
  echo "[FAIL] ${n}/${RETRIES}"
done
exit 1
