---

name: Ansible Standard
on:
  pull_request:
  push:
    branches:
      - master
    tags:
      - '[0-9]+.[0-9]+'
      - '[0-9]+.[0-9]+*'

jobs:
  test:

    runs-on: ubuntu-latest

    strategy:
      matrix:
        # Adding all targets and only run them if they exist.
        # Prevents us from forgetting to update this in case
        # we add new envs in terragrunt.
        version:
          - "2.3"
          - "2.4"
          - "2.5"
          - "2.6"
          - "2.7"
          - "2.8"
          - latest
        flavour:
          - base
          - tools
          - infra
          - azure
          - aws
          - awsk8s

    name: "[ Ansible ${{ matrix.version }} (${{ matrix.flavour }}) ]"
    steps:

      - name: Checkout repository
        uses: actions/checkout@master

      - name: Show environment
        run: |
          env

      - name: Build
        run: |
          retry() {
            for ((n=0; n<10; n++)); do
              echo "[${n}] ${*}";
              if eval "${*}"; then
                return 0;
              fi;
            done;
            return 1;
          }
          if [ "${FLAVOUR}" = "base" ]; then
            retry make build TAG=${VERSION}
          else
            retry make build TAG=${VERSION}-${FLAVOUR}
          fi
        env:
          VERSION: ${{ matrix.version }}
          FLAVOUR: ${{ matrix.flavour }}

      - name: Test
        run: |
          retry() {
            for ((n=0; n<10; n++)); do
              echo "[${n}] ${*}";
              if eval "${*}"; then
                return 0;
              fi;
            done;
            return 1;
          }
          if [ "${FLAVOUR}" = "base" ]; then
            retry make test TAG=${VERSION}
          else
            retry make test TAG=${VERSION}-${FLAVOUR}
          fi
          retry make test TAG=${VERSION}
        env:
          VERSION: ${{ matrix.version }}
          FLAVOUR: ${{ matrix.flavour }}
