---

name: Ansible Base

on:
  - pull_request
  - push

jobs:
  test:
    runs-on: ubuntu-latest

    strategy:
      matrix:
        # Adding all targets and only run them if they exist.
        # Prevents us from forgetting to update this in case
        # we add new envs in terragrunt.
        ansible:
          - 2.3
          - 2.4
          - 2.5
          - 2.6
          - 2.7
          - 2.8
          - latest

    name: "[ Ansible base ${{ matrix.ansible }} ]"
    steps:

      - name: Checkout repository
        uses: actions/checkout@master

      - name: Show environment
        run: |
          env
          git branch
          git remote -v

      - name: Build
        run: |
          retry() {
            for ((n=0; n<10; n++)); do
              echo "[${n}] ${*}";
              if eval "${*}"; then
                return 0;
              fi;
            done;
            return 1;
          }
          retry make build TAG=${VERSION}
        env:
          VERSION: ${{ matrix.ansible }}

      - name: Test
        run: |
          retry() {
            for ((n=0; n<10; n++)); do
              echo "[${n}] ${*}";
              if eval "${*}"; then
                return 0;
              fi;
            done;
            return 1;
          }
          retry make test TAG=${VERSION}
        env:
          VERSION: ${{ matrix.ansible }}
