---

###
### Lints all generic and json files in the whole git repository
###

name: linting
on:
  pull_request:
  push:
    branches:
      - master
    tags:
      - '[0-9]+.[0-9]+'
      - '[0-9]+.[0-9]+*'

jobs:
  lint:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        job: [generic]

    name: "[ ${{ matrix.job }} ]"
    steps:
      - name: Checkout repository
        uses: actions/checkout@master

      - name: Lint
        run: |
          make "lint"
        env:
          job: ${{ matrix.job }}

      # Only run this, if the PR was created by the repo owner
      - name: Publish image (only repo owner)
        run:
          echo "test"
        if: github.event.repository.owner.id == github.event.pull_request.user.id
