---

# -------------------------------------------------------------------------------------------------
# Job Name
# -------------------------------------------------------------------------------------------------
name: params


# -------------------------------------------------------------------------------------------------
# Custom Variables
# -------------------------------------------------------------------------------------------------
env:
  VERSIONS: >-
    [
      {
        "NAME": "ansible",
        "VERSION": [
          "latest",
          "2.20",
          "2.19",
          "2.18",
          "2.17",
          "2.16",
          "2.15",
          "2.14",
          "2.13"
        ],
        "KOPS": [
          "1.34",
          "1.33",
          "1.32",
          "1.31",
          "1.30"
        ],
        "HELM": [
          "3.20",
          "3.19",
          "3.18",
          "3.17",
          "3.16",
          "3.15",
          "3.14",
          "3.13",
          "3.12",
          "3.11"
        ],
        "FLAVOUR": ["default"],
        "ARCH":    ["linux/amd64", "linux/arm64"]
      }
    ]

  # Set Refs to build for scheduled jobs.
  REFS: >-
    {
      "DEFAULT_BRANCH": "master",
      "BRANCHES": "master",
      "NUM_LATEST_TAGS": 0
    }


# -------------------------------------------------------------------------------------------------
# When to run
# -------------------------------------------------------------------------------------------------
on:
  workflow_call:
    outputs:
      versions:
        description: "Stringified JSON of Versions definition."
        value: ${{ jobs.params.outputs.versions }}
      refs:
        description: "Stringified JSON of Refs definition."
        value: ${{ jobs.params.outputs.refs }}

jobs:
  params:
    runs-on: ubuntu-latest

    outputs:
      versions: ${{ steps.set-json.outputs.versions }}
      refs: ${{ steps.set-json.outputs.refs }}

    steps:
      - name: "[Set-Output] JSON"
        id: set-json
        run: |
          VERSIONS="$( echo '${{ env.VERSIONS }}' | jq -M -c )"
          REFS="$( echo '${{ env.REFS }}' | jq -M -c )"

          echo "versions=${VERSIONS}" >> $GITHUB_OUTPUT
          echo "refs=${REFS}"         >> $GITHUB_OUTPUT

      - name: "[DEBUG] Show settings'"
        run: |
          echo 'Versions'
          echo '--------------------'
          echo '${{ steps.set-json.outputs.versions }}'
          echo

          echo 'Refs'
          echo '--------------------'
          echo '${{ steps.set-json.outputs.refs }}'
          echo
